### PR TITLE
Added GetTotalCount method

### PR DESCRIPTION
**Pull request by gtaylor44**
How about something like this?

### CODE REVIEW

**Comment by gtaylor44** [comment]
#171

**Comment by XiaoFaye** [comment]
I believe the header values should be in webresponse.header 

image

**Comment by XiaoFaye** [comment]
I think something like `Action<HttpWebRequest> requestFilter = null` in RestAPI would be better as it's more flexible for different users.

**Comment by Thieund** [comment]
GetTotalCount is the per-request value, while requestFiler is property of the RestAPI.  How can map the total to the right request ?

**Comment by XiaoFaye** [comment]
@Thieund  If you want to get the value of X-WP-Total or X-WP-TotalPages, you should be able to do it in responseFilter

**Comment by Thieund** [comment]
@XiaoFaye Is it better if responseFilter is a param of each request as well ? If RestAPI is shared between multiple requests, how can we distinguish their response header values ?

**Pull request closed without merging**
