### PR TITLE
Update BaseObject.cs

### PR DESCRIPTION
**Pull request by teunlielu**
Conversie Throubles: see error #152 and #147

### CODE REVIEW

**Comment by goguvi** [comment]
You're converting all decimal values to string in your code. I don't know if is correct to do so. 
The API Docs say:

> Any decimal monetary amount, such as prices or totals, will be returned as strings with two decimal places.

I didn't find any property returned as decimal value, but it may appear on future versions

**Comment by teunlielu** [comment]
Then possible you have problem. But so works. Bug free.
At  moment have Woocermece  no decimal values. 
Best of Woocermece change prices etc to decimal values in V3 and not woking string

**Comment by teunlielu** [comment]
Your option is oke:

      objValue.SetValue(this, (pi.GetValue(this) as decimal?).Value.ToString(CultureInfo.InvariantCulture));

**Comment by XiaoFaye** [comment]
@teunlielu  Yes, in v2, all decimal values should be appear as string in JSON.

**Comment by teunlielu** [comment]
Yes then works my soulision. Oke. I think we must fixed. What now is bug

**Comment by goguvi** [comment]
It seems that it have been like that since legacy API http://woocommerce.github.io/woocommerce-rest-api-docs/v1.html#responses

> - Any decimal monetary amount, such as prices or totals, are returned as strings with two decimal places. The decimal separator (typically either . or ,) is controlled by the site and is included in the API index. This is by design, in order to make localization of API data easier for the client. You may need to account for this in your implemetation if you will be doing calculations with the returned data (e.g. convert string amounts with commas as the decimal place before performing any calculations)
> 
>- Other amounts, such as item counts, are returned as integers.

So I think it's right to assume that decimals will continue to be implemented as string.

@teunlielu notice that JsonObject class is inherited from Legacy API too, so I think it has to be backwards compatible.

**Comment by teunlielu** [comment]
no problem: but code of now make from 2,15 or 2.15 in "215" and it must "2.15". that wrong.
that what mean. or code fiexed, if this problem with  Legacy API: the we must implation for V1 and V2 and legacy API.  @XiaoFaye @goguvi

**Comment by goguvi** [comment]
The docs of both Legacy and current API all decimals amounts are strings, so I think there will be no problem changing it.

**Comment by XiaoFaye** [comment]
@teunlielu @goguvi  Deserialize should be all good, the problem is Serialize, previously, it accepts decimal value in json as `price:13.50` , not it only accepts `price:"13.50"`.

**Comment by teunlielu** [comment]
objValue.SetValue(this, decimal.Parse(pi.GetValue(this).ToString(), CultureInfo.InvariantCulture));
                    }
Works in councry with a dot oke but not  comma
objValue.SetValue(this, decimal.Parse("12,5" ,CultureInfo.InvariantCulture));
                    }
See you it? And will convert to decimal is a 125 remove comma. You must parce to decimal and then to string with CultureInfo.InvariantCulture

**Comment by teunlielu** [comment]
objValue.SetValue(this, decimal.Parse("12,5" ,CultureInfo.InvariantCulture));
} is an example how works compiler

**Comment by goguvi** [comment]
@teunlielu I think both @XiaoFaye and me understand the problem (I said it myself in #152). But I think it is worth reviewing well to which versions it affects and if it can cause any problems in any of them.

Testing I have seen that the legacy API effectively sets string and decimal prices correctly. For example from "10.5", "10,5" and 10.5 the JSON returns "10.5".

V1 and V2 of the new API however returns:
```
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter: regular_price",
  "data": {
    "status": 400,
    "params": {
      "regular_price": "regular_price is not of type string."
    }
  }
}
```
Despite of this and since both accept string, I think that changing the decimals to string, as requested in the pull request, would be correct. However it is important to correct that the decimals don't disappear for some cultures (even if the value is kept as decimal)

**Pull request merged**
