### PR TITLE
Update RestAPI.cs

### PR DESCRIPTION
**Pull request by acerov**
Woocommerce API with JWT token

resolves this issue:
https://github.com/XiaoFaye/WooCommerce.NET/issues/478

### CODE REVIEW

**Comment by XiaoFaye** [comment]
Thanks for the PR!

Have you checked this will work for both Wordpress & WooCommerce API under Nginx or Apache?

**Comment by acerov** [comment]
Iz works but for Woocommerce API token must be copied from WordPress API.
When I have some time today I will try to make some changes so Woocommerce API fills token by itself. Will let you know.

**Comment by acerov** [comment]
Made some more changes in RestAPI.cs

Idea is to try to get JWT token also when using Woocommerce API and username/password.
If JWT token is obtained then use it as authorization method, otherwise use basic authorization.

**Comment by acerov** [comment]
Hi XiaoFaye,

please check the changes and merge if you think it is ok.

**Comment by XiaoFaye** [comment]
Thanks for the idea!

**Comment by acerov** [comment]
Glad I can help, thank you for the project, it does the job well!

**Pull request merged**
